<?php

return [
    [
        'id' => 1,
        'slug' => 'batik-tulis-parang-klasik',
        'sku' => 'BP-001',
        'name' => 'Batik Tulis Parang Klasik',
        'price' => 'Rp250.000',
        'img' => 'product-01.jpg',
        'cat' => 'women',
        'cat_label' => 'Batik Wanita',
        'description' => 'Batik tulis dengan motif Parang, salah satu motif klasik keraton Yogyakarta yang melambangkan keteguhan hati dan kesinambungan. Dibuat dengan teknik canting oleh pengrajin senior.',
        'weight' => '0,3 kg',
        'material' => 'Katun Primisima',
        'colors' => ['Cokelat Sogan', 'Hitam'],
        'sizes' => ['S', 'M', 'L', 'XL'],
    ],
    [
        'id' => 2,
        'slug' => 'batik-cap-kawung-premium',
        'sku' => 'BP-002',
        'name' => 'Batik Cap Kawung Premium',
        'price' => 'Rp350.000',
        'img' => 'product-02.jpg',
        'cat' => 'women',
        'cat_label' => 'Batik Wanita',
        'description' => 'Batik cap motif Kawung dengan warna pekalongan pesisiran yang cerah. Cocok untuk acara semi-formal maupun harian.',
        'weight' => '0,35 kg',
        'material' => 'Katun dobby',
        'colors' => ['Biru', 'Hijau'],
        'sizes' => ['S', 'M', 'L', 'XL'],
    ],
    [
        'id' => 3,
        'slug' => 'kemeja-batik-mega-mendung',
        'sku' => 'BP-003',
        'name' => 'Kemeja Batik Mega Mendung',
        'price' => 'Rp275.000',
        'img' => 'product-03.jpg',
        'cat' => 'men',
        'cat_label' => 'Batik Pria',
        'description' => 'Kemeja batik pria motif Mega Mendung khas Cirebon dengan gradasi warna awan yang elegan. Potongan regular fit untuk kenyamanan seharian.',
        'weight' => '0,4 kg',
        'material' => 'Katun halus',
        'colors' => ['Biru', 'Merah'],
        'sizes' => ['M', 'L', 'XL', 'XXL'],
    ],
    [
        'id' => 4,
        'slug' => 'outer-batik-wanita-elegan',
        'sku' => 'BP-004',
        'name' => 'Outer Batik Wanita Elegan',
        'price' => 'Rp450.000',
        'img' => 'product-04.jpg',
        'cat' => 'women',
        'cat_label' => 'Batik Wanita',
        'description' => 'Outer longgar dengan panel batik tulis di bagian depan dan lengan. Cocok dipadu dengan dress polos atau celana kerja.',
        'weight' => '0,5 kg',
        'material' => 'Katun rayon',
        'colors' => ['Hitam', 'Cokelat'],
        'sizes' => ['S', 'M', 'L', 'XL'],
    ],
    [
        'id' => 5,
        'slug' => 'blouse-batik-sogan',
        'sku' => 'BP-005',
        'name' => 'Blouse Batik Sogan',
        'price' => 'Rp320.000',
        'img' => 'product-05.jpg',
        'cat' => 'women',
        'cat_label' => 'Batik Wanita',
        'description' => 'Blouse motif Sogan klasik dengan pewarna alami tegeran dan soga. Nuansa hangat dan berkelas.',
        'weight' => '0,3 kg',
        'material' => 'Katun primisima',
        'colors' => ['Cokelat Sogan'],
        'sizes' => ['S', 'M', 'L', 'XL'],
    ],
    [
        'id' => 6,
        'slug' => 'scarf-batik-sutra-lukis',
        'sku' => 'BP-006',
        'name' => 'Scarf Batik Sutra Lukis',
        'price' => 'Rp180.000',
        'img' => 'product-06.jpg',
        'cat' => 'watches',
        'cat_label' => 'Aksesoris',
        'description' => 'Scarf batik lukis dari kain sutra asli dengan sentuhan lembut di kulit. Ukuran 50 x 150 cm.',
        'weight' => '0,15 kg',
        'material' => 'Sutra ATBM',
        'colors' => ['Ungu', 'Merah', 'Biru'],
        'sizes' => ['All Size'],
    ],
    [
        'id' => 7,
        'slug' => 'dress-batik-cirebon',
        'sku' => 'BP-007',
        'name' => 'Dress Batik Cirebon',
        'price' => 'Rp495.000',
        'img' => 'product-07.jpg',
        'cat' => 'women',
        'cat_label' => 'Batik Wanita',
        'description' => 'Dress panjang dengan motif pesisir Cirebon, detail lengan balon dan tali pinggang yang memperkuat siluet.',
        'weight' => '0,55 kg',
        'material' => 'Katun rayon premium',
        'colors' => ['Biru', 'Merah'],
        'sizes' => ['S', 'M', 'L', 'XL'],
    ],
    [
        'id' => 8,
        'slug' => 'selendang-batik-pesisir',
        'sku' => 'BP-008',
        'name' => 'Selendang Batik Pesisir',
        'price' => 'Rp195.000',
        'img' => 'product-08.jpg',
        'cat' => 'women',
        'cat_label' => 'Aksesoris',
        'description' => 'Selendang batik pesisiran dengan warna cerah, cocok untuk padanan kebaya atau gaun malam.',
        'weight' => '0,2 kg',
        'material' => 'Katun tipis',
        'colors' => ['Merah', 'Kuning', 'Pink'],
        'sizes' => ['All Size'],
    ],
    [
        'id' => 9,
        'slug' => 'sepatu-motif-batik',
        'sku' => 'BP-009',
        'name' => 'Sepatu Motif Batik',
        'price' => 'Rp425.000',
        'img' => 'product-09.jpg',
        'cat' => 'shoes',
        'cat_label' => 'Alas Kaki',
        'description' => 'Sneakers dengan aksen batik pada upper. Nyaman dipakai harian sekaligus menunjukkan identitas nusantara.',
        'weight' => '0,9 kg',
        'material' => 'Canvas + kulit sintetis',
        'colors' => ['Hitam', 'Putih'],
        'sizes' => ['38', '39', '40', '41', '42', '43'],
    ],
    [
        'id' => 10,
        'slug' => 'tunik-batik-lereng',
        'sku' => 'BP-010',
        'name' => 'Tunik Batik Lereng',
        'price' => 'Rp285.000',
        'img' => 'product-10.jpg',
        'cat' => 'women',
        'cat_label' => 'Batik Wanita',
        'description' => 'Tunik longgar dengan motif Lereng khas Solo, nyaman dipakai untuk kerja maupun santai.',
        'weight' => '0,35 kg',
        'material' => 'Katun rayon',
        'colors' => ['Biru', 'Hijau'],
        'sizes' => ['S', 'M', 'L', 'XL'],
    ],
    [
        'id' => 11,
        'slug' => 'kemeja-batik-sogan-jogja',
        'sku' => 'BP-011',
        'name' => 'Kemeja Batik Sogan Jogja',
        'price' => 'Rp395.000',
        'img' => 'product-11.jpg',
        'cat' => 'men',
        'cat_label' => 'Batik Pria',
        'description' => 'Kemeja batik pria dengan motif Sogan klasik gaya Jogja. Potongan slim fit, cocok untuk acara formal.',
        'weight' => '0,4 kg',
        'material' => 'Katun primisima',
        'colors' => ['Cokelat Sogan'],
        'sizes' => ['M', 'L', 'XL', 'XXL'],
    ],
    [
        'id' => 12,
        'slug' => 'kemeja-batik-truntum',
        'sku' => 'BP-012',
        'name' => 'Kemeja Batik Truntum',
        'price' => 'Rp385.000',
        'img' => 'product-12.jpg',
        'cat' => 'men',
        'cat_label' => 'Batik Pria',
        'description' => 'Motif Truntum melambangkan cinta yang tumbuh kembali. Pilihan tepat untuk acara pernikahan dan lamaran.',
        'weight' => '0,4 kg',
        'material' => 'Katun primisima',
        'colors' => ['Hitam', 'Cokelat'],
        'sizes' => ['M', 'L', 'XL', 'XXL'],
    ],
    [
        'id' => 13,
        'slug' => 'atasan-batik-remaja',
        'sku' => 'BP-013',
        'name' => 'Atasan Batik Remaja',
        'price' => 'Rp245.000',
        'img' => 'product-13.jpg',
        'cat' => 'women',
        'cat_label' => 'Batik Wanita',
        'description' => 'Atasan batik modern dengan potongan crop dan bahan ringan, cocok untuk gaya anak muda.',
        'weight' => '0,25 kg',
        'material' => 'Katun rayon',
        'colors' => ['Pink', 'Hijau'],
        'sizes' => ['S', 'M', 'L'],
    ],
    [
        'id' => 14,
        'slug' => 'gamis-batik-modern',
        'sku' => 'BP-014',
        'name' => 'Gamis Batik Modern',
        'price' => 'Rp550.000',
        'img' => 'product-14.jpg',
        'cat' => 'women',
        'cat_label' => 'Batik Wanita',
        'description' => 'Gamis panjang dengan kombinasi kain batik pada bagian bawah dan polos pada bagian atas, dilengkapi tali pinggang.',
        'weight' => '0,6 kg',
        'material' => 'Katun rayon premium',
        'colors' => ['Hitam', 'Navy'],
        'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
    ],
    [
        'id' => 15,
        'slug' => 'tas-batik-handmade',
        'sku' => 'BP-015',
        'name' => 'Tas Batik Handmade',
        'price' => 'Rp325.000',
        'img' => 'product-15.jpg',
        'cat' => 'bag',
        'cat_label' => 'Tas',
        'description' => 'Tas jinjing dengan panel batik tulis di bagian luar dan lapisan kulit sintetis tahan air.',
        'weight' => '0,7 kg',
        'material' => 'Katun + kulit sintetis',
        'colors' => ['Cokelat', 'Hitam'],
        'sizes' => ['30 x 25 x 10 cm'],
    ],
    [
        'id' => 16,
        'slug' => 'blus-batik-floral',
        'sku' => 'BP-016',
        'name' => 'Blus Batik Floral',
        'price' => 'Rp275.000',
        'img' => 'product-16.jpg',
        'cat' => 'women',
        'cat_label' => 'Batik Wanita',
        'description' => 'Blus batik motif floral dengan nuansa pesisir, ringan dan jatuh sempurna di badan.',
        'weight' => '0,3 kg',
        'material' => 'Katun rayon',
        'colors' => ['Merah', 'Pink'],
        'sizes' => ['S', 'M', 'L', 'XL'],
    ],
];
